<?php

namespace TomatoPHP\FilamentEmployees\Filament\Resources\AccountResource\Pages;

use TomatoPHP\FilamentEmployees\Filament\Resources\AccountResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditAccount extends EditRecord
{
    protected static string $resource = AccountResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }


    protected function mutateFormDataBeforeFill(array $data): array
    {
        $meta = $this->getRecord()->accountsMetas()->pluck('value', 'key')->toArray();
        return array_merge($data, $meta); // TODO: Change the autogenerated stub
    }

    public function afterSave()
    {
        $meta = collect($this->form->getState())->filter(function ($value, $key) {
            return !in_array($key, ['name', 'email', 'phone', 'address', 'is_login', 'password', 'password_confirmation', 'type', 'username']);
        })->toArray();

        foreach ($meta as $key=>$value){
            $this->getRecord()->meta($key, $value);
        }
    }
}
