<?php

namespace TomatoPHP\FilamentEmployees\Filament\Resources\EmployeeResource\Pages;

use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;
use TomatoPHP\FilamentEmployees\Filament\Resources\EmployeeResource;

class EditAccount extends EditRecord
{
    protected static string $resource = EmployeeResource::class;

    protected function getHeaderActions(): array
    {
        return [
            DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $meta = $this->getRecord()->modelMeta()->pluck('value', 'key')->toArray();

        return array_merge($data, $meta); // TODO: Change the autogenerated stub
    }

    public function afterSave()
    {
        $meta = collect($this->form->getState())->filter(function ($value, $key) {
            return ! in_array($key, ['name', 'email', 'phone', 'address', 'is_login', 'password', 'password_confirmation', 'type', 'username']);
        })->toArray();

        foreach ($meta as $key => $value) {
            $this->getRecord()->meta($key, $value);
        }
    }
}
