<?php

namespace TomatoPHP\FilamentEmployees\Filament\Resources;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules\Password;
use TomatoPHP\FilamentAccounts\Components\AccountColumn;
use TomatoPHP\FilamentEmployees\Filament\Resources\EmployeeResource\Pages\EditAccount;
use TomatoPHP\FilamentEmployees\Filament\Resources\EmployeeResource\Pages\ListAccounts;
use TomatoPHP\FilamentEmployees\Filament\Resources\EmployeeResource\RelationManagers\EmployeeAttendanceRelation;
use TomatoPHP\FilamentEmployees\Filament\Resources\EmployeeResource\RelationManagers\EmployeePaymentRelation;
use TomatoPHP\FilamentEmployees\Filament\Resources\EmployeeResource\RelationManagers\EmployeePayrollRelation;
use TomatoPHP\FilamentEmployees\Filament\Resources\EmployeeResource\RelationManagers\EmployeeRequestRelation;
use TomatoPHP\FilamentEmployees\Models\AttendanceShift;
use TomatoPHP\FilamentTypes\Models\Type;

class EmployeeResource extends Resource
{
    protected static ?string $model = null;

    public static function getModel(): string
    {
        return config('filament-accounts.model'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationGroup(): ?string
    {
        return 'HRMS';
    }

    public static function getPluralLabel(): ?string
    {
        return 'Employees';
    }

    public static function getLabel(): ?string
    {
        return 'Employee';
    }

    public static function getNavigationLabel(): string
    {
        return 'Employees';
    }

    protected static string|\BackedEnum|null $navigationIcon = 'heroicon-o-user-circle';

    public static function form(Schema $schema): Schema
    {
        return $schema
            ->components(fn ($record) => $record ? [
                Grid::make([
                    'md' => 12,
                    'sm' => 1,
                ])->columnSpanFull()
                    ->schema([
                        Grid::make(1)
                            ->schema([
                                Section::make('Main Info')
                                    ->schema([
                                        SpatieMediaLibraryFileUpload::make('avatar')
                                            ->collection('avatar')
                                            ->columnSpan(2)
                                            ->avatar()
                                            ->image()
                                            ->alignCenter()
                                            ->hiddenLabel()
                                            ->label(trans('filament-accounts::messages.accounts.columns.avatar')),
                                        TextInput::make('name')
                                            ->columnSpanFull()
                                            ->maxLength(255),
                                        TextInput::make('email')
                                            ->email()
                                            ->afterStateUpdated(function (Set $set, Get $get) {
                                                $set('username', $get('email'));
                                            })
                                            ->lazy()
                                            ->unique('accounts', 'email', ignorable: fn ($record) => $record)
                                            ->maxLength(255),
                                        Hidden::make('username'),
                                        Hidden::make('type')->default('employee'),
                                        TextInput::make('phone')
                                            ->tel()
                                            ->maxLength(255),
                                        Textarea::make('address')
                                            ->columnSpanFull(),
                                    ])
                                    ->columns(2),
                                Section::make('National Info')
                                    ->schema([
                                        TextInput::make('first_name'),
                                        TextInput::make('middle_name'),
                                        TextInput::make('last_name'),
                                        TextInput::make('position')->columnSpanFull(),
                                        TextInput::make('nationality'),
                                        Select::make('national_id_type')
                                            ->searchable()
                                            ->options([
                                                'id' => 'ID',
                                                'passport' => 'Passport',
                                                'visa' => 'Visa',
                                            ])
                                            ->default('id'),
                                        TextInput::make('national_id')
                                            ->numeric(),
                                        DatePicker::make('brithday')->date(),
                                        Select::make('geneder')
                                            ->options([
                                                'male' => 'Male',
                                                'female' => 'Female',
                                            ]),

                                        TextInput::make('vacations')
                                            ->numeric()
                                            ->default(0),
                                        DatePicker::make('contract_start'),
                                        DatePicker::make('contract_end'),
                                        Select::make('status')
                                            ->options([
                                                'active' => 'Active',
                                                'inactive' => 'Inactive',
                                                'suspended' => 'Suspended',
                                                'terminated' => 'Terminated',
                                            ]),
                                    ])->columns(3),
                                Section::make('Education')
                                    ->schema([
                                        Toggle::make('has_education')
                                            ->live()
                                            ->columnSpanFull()
                                            ->default(false),
                                        Select::make('education_type')
                                            ->default('university')
                                            ->options([
                                                'school' => 'School',
                                                'university' => 'University',
                                                'college' => 'College',
                                            ])
                                            ->visible(fn (Get $get) => $get('has_education')),
                                        TextInput::make('university')
                                            ->visible(fn (Get $get) => $get('has_education')),
                                        TextInput::make('college')
                                            ->visible(fn (Get $get) => $get('has_education')),
                                        TextInput::make('college_department')
                                            ->visible(fn (Get $get) => $get('has_education')),
                                    ])->columns(2),
                                Section::make('CV')
                                    ->schema([
                                        Toggle::make('has_links')
                                            ->live()
                                            ->default(false),
                                        Repeater::make('links')
                                            ->visible(fn (Get $get) => $get('has_links'))
                                            ->schema([
                                                TextInput::make('name'),
                                                TextInput::make('link'),
                                            ]),
                                    ]),
                            ])
                            ->columnSpan(8),
                        Grid::make(1)
                            ->schema([
                                Section::make('Auth')
                                    ->schema([
                                        Toggle::make('is_active')
                                            ->required(),
                                        Toggle::make('is_login')
                                            ->default(false)
                                            ->live(),
                                        TextInput::make('password')
                                            ->confirmed()
                                            ->hidden(fn (Get $get) => ! $get('is_login'))
                                            ->rule(Password::default())
                                            ->dehydrateStateUsing(fn ($state) => Hash::make($state))
                                            ->same('password_confirmation')
                                            ->revealable(filament()->arePasswordsRevealable())
                                            ->password()
                                            ->maxLength(255),
                                        TextInput::make('password_confirmation')
                                            ->hidden(fn (Get $get) => ! $get('is_login'))
                                            ->password()
                                            ->revealable(filament()->arePasswordsRevealable())
                                            ->required()
                                            ->dehydrated(false),
                                    ]),
                                Section::make('Attendance')
                                    ->schema([
                                        Select::make('department')
                                            ->label('Department')
                                            ->searchable()
                                            ->live()
                                            ->preload()
                                            ->options(Type::query()->where('for', 'employees')->where('type', 'departments')->pluck('name', 'key')->toArray())
                                            ->nullable(),
                                        Select::make('attendance_shift_id')
                                            ->disabled(fn (Get $get) => ! $get('department'))
                                            ->label('Attendance Shift')
                                            ->searchable()
                                            ->options(fn (Get $get) => AttendanceShift::query()->where('department', $get('department'))->pluck('name', 'id')->toArray())
                                            ->nullable(),
                                    ]),
                                Section::make('Salary')
                                    ->schema([
                                        TextInput::make('salary')->numeric(),
                                        TextInput::make('salary_subscription')->numeric(),
                                        TextInput::make('salary_tax')->numeric(),
                                        Select::make('salary_period')
                                            ->options([
                                                'hour' => 'Hour',
                                                'day' => 'Day',
                                                'week' => 'Week',
                                                'month' => 'Month',
                                                'year' => 'Year',
                                            ]),
                                    ]),
                                Section::make('Bank')
                                    ->schema([
                                        Toggle::make('has_bank_account')
                                            ->live()
                                            ->default(false),
                                        TextInput::make('bank_name')
                                            ->visible(fn (Get $get) => $get('has_bank_account')),
                                        TextInput::make('bank_branch')
                                            ->visible(fn (Get $get) => $get('has_bank_account')),
                                        TextInput::make('bank_iban')
                                            ->visible(fn (Get $get) => $get('has_bank_account')),
                                        TextInput::make('bank_swift')
                                            ->visible(fn (Get $get) => $get('has_bank_account')),
                                        TextInput::make('bank_account')
                                            ->visible(fn (Get $get) => $get('has_bank_account')),
                                    ]),
                                Section::make('Insurance')
                                    ->schema([
                                        Toggle::make('has_insurance')
                                            ->live()
                                            ->default(false),
                                        TextInput::make('insurance_number')
                                            ->visible(fn (Get $get) => $get('has_insurance')),
                                        Toggle::make('has_medical_insurance')
                                            ->live()
                                            ->default(false),
                                        TextInput::make('medical_insurance_company')
                                            ->visible(fn (Get $get) => $get('has_medical_insurance')),
                                        TextInput::make('medical_insurance_number')
                                            ->visible(fn (Get $get) => $get('has_medical_insurance')),
                                        DatePicker::make('medical_insurance_start_at')
                                            ->visible(fn (Get $get) => $get('has_medical_insurance')),
                                        DatePicker::make('medical_insurance_end_at')
                                            ->visible(fn (Get $get) => $get('has_medical_insurance')),
                                    ]),

                            ])
                            ->columnSpan(4),
                    ]),

            ] : [
                SpatieMediaLibraryFileUpload::make('avatar')
                    ->collection('avatar')
                    ->columnSpan(2)
                    ->avatar()
                    ->image()
                    ->alignCenter()
                    ->hiddenLabel()
                    ->label(trans('filament-accounts::messages.accounts.columns.avatar')),
                TextInput::make('name')
                    ->columnSpanFull()
                    ->maxLength(255),
                TextInput::make('email')
                    ->email()
                    ->afterStateUpdated(function (Set $set, Get $get) {
                        $set('username', $get('email'));
                    })
                    ->lazy()
                    ->unique('accounts', 'email', ignorable: fn ($record) => $record)
                    ->maxLength(255),
                Hidden::make('username'),
                Hidden::make('type')->default('employee'),
                TextInput::make('phone')
                    ->tel()
                    ->maxLength(255),
                Textarea::make('address')
                    ->columnSpanFull(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(function (Builder $query) {
                $query->where('type', 'employee');
            })
            ->columns([
                AccountColumn::make('id')
                    ->label(trans('filament-accounts::messages.accounts.columns.id')),
                TextColumn::make('name')
                    ->label(trans('filament-accounts::messages.accounts.columns.name'))
                    ->toggleable()
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable()
                    ->searchable(),
                TextColumn::make('email')
                    ->label(trans('filament-accounts::messages.accounts.columns.email'))
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable()
                    ->searchable(),
                TextColumn::make('phone')
                    ->label(trans('filament-accounts::messages.accounts.columns.phone'))
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable()
                    ->searchable(),
                IconColumn::make('is_login')
                    ->label(trans('filament-accounts::messages.accounts.columns.is_login'))
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable()
                    ->boolean(),
                IconColumn::make('is_active')
                    ->label(trans('filament-accounts::messages.accounts.columns.is_active'))
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable()
                    ->boolean(),
                TextColumn::make('deleted_at')
                    ->sortable()
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('created_at')
                    ->sortable()
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->sortable()
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            EmployeeAttendanceRelation::class,
            EmployeePaymentRelation::class,
            EmployeeRequestRelation::class,
            EmployeePayrollRelation::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListAccounts::route('/'),
            'edit' => EditAccount::route('/{record}/edit'),
        ];
    }
}
